name: Benchmarks

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install gungraun-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )
          cargo install gungraun-runner --version $version

      # - name: Checkout main branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Run benchmark on PR
        run: cargo bench
    
      # # Upload report as PR comment
      # - name: Post benchmark report
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     path: bench_report.txt
