name: Benchmarks

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Valgrind (required for iai-callgrind)
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install iai-callgrind-runner
        run: cargo install iai-callgrind-runner

      # - name: Checkout main branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Build benchmark on PR
        run: cargo build --release --bin my_benchmark

      - name: Run benchmark on PR
        run: iai-callgrind-runner target/release/my_benchmark --save-baseline pr
    
      # # Upload report as PR comment
      # - name: Post benchmark report
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     path: bench_report.txt
