name: Benchmarks

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Valgrind (required for iai-callgrind)
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install iai-callgrind-runner
        run: cargo install iai-callgrind-runner

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run benchmarks on main branch
        run: cargo bench -- --save-baseline main

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Run benchmarks on PR branch
        run: cargo bench -- --save-baseline pr

      - name: Compare benchmark results
        run: cargo bench -- --baseline main --baseline pr

      # Upload report as PR comment
      - name: Post benchmark report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "test message"
