name: Benchmarks

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install gungraun-runner
        run: cargo install gungraun-runner

      # - name: Checkout main branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Run benchmark on PR
        run: cargo bench
    
      # # Upload report as PR comment
      # - name: Post benchmark report
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     path: bench_report.txt
