name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Check Fmt
      run: cargo fmt --all -- --check

  check_lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Run Check
      run: cargo check --all-targets --all-features
      env:
        RUSTFLAGS: "-D warnings"

  clippy_lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      run: cargo clippy -- -D warnings

  build_and_test_debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Run tests in debug
      run: cargo test --verbose

  build_and_test_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Run tests
      run: cargo test --release --verbose
